spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gerenciador-oficina-notificacao
    username: postgres
    password: totvs@123

management:
  health:
    mail:
      enabled: false

email:
  enabled: false

logging:
  level:
    org.springframework.amqp: DEBUG
